package com.example.csit228f2_2.Server;

public enum Status {
    LOGIN_SUCCESS, USERNAME_NOT_FOUND, INCORRECT_PASSWORD, ACCOUNT_CREATED_SUCCESSFULLY, ACCOUNT_CREATION_FAILED,
    ACCOUNT_UPDATED_SUCCESSFULLY, ACCOUNT_UPDATE_FAILED, ACCOUNT_DELETION_FAILED, ACCOUNT_DELETED_SUCCESSFULLY,
    TASK_CREATED_SUCCESSFULLY, TASK_CREATION_FAILED, TASK_DELETED_SUCCESSFULLY, TASK_DELETION_FAILED, USER_DOES_NOT_EXIST, TASK_EDITED_SUCCESSFULLY, TASK_EDIT_FAILED
}